version: '3'
services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile.server
    container_name: server
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
    expose:
      - 8080

  client:
    build:
      context: .
      dockerfile: ./Dockerfile.client
    container_name: client
    environment:
      - SERVER_HOST=server
      - SERVER_PORT=8080
    depends_on:
      - server