package proto

// Operation - server and client communication steps
type Operation byte

const (
	// Initiate - empty request from client to start communication
	Initiate Operation = 1
	// SendChallenge - sending challenge generated by server to client
	SendChallenge Operation = 2
	// SendNonce - sending resolved challenge from client to server
	SendNonce Operation = 3
	// SendData - sending data from server to client
	SendData Operation = 4
)
